name: step_win_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  google_sign_in: ^6.1.5
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/design/

# Icon configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/design/app_icon.png"
  min_sdk_android: 21

# Splash screen configuration
flutter_native_splash:
  color: "#6B46C1"
  color_dark: "#1F1B24"
  android_12:
    icon_background_color: "#6B46C1"
    icon_background_color_dark: "#1F1B24"